export const permissionsFR = {
    CREATE_INSTANT_INVITE: 'Permet la création d\'invitations instantanées',
    KICK_MEMBERS: 'Permet d\'expulser des membres',
    BAN_MEMBERS: 'Permet de banir des membres',
    ADMINISTRATOR: 'Autorise toutes les autorisations et contourne les écrasements d’autorisations de canal',
    MANAGE_CHANNELS: 'Permet la gestion et l\'édition des canaux',
    MANAGE_GUILD: 'Permet la gestion et l\'édition de la guilde',
    ADD_REACTIONS: 'Permet l\'ajout de réactions aux messages',
    VIEW_AUDIT_LOG: 'Permet de visualiser les journaux d\'audit',
    PRIORITY_SPEAKER: 'Permet d\'utiliser le haut-parleur prioritaire dans un canal vocal',
    STREAM: 'Permet à l\'utilisateur d\'aller en direct',
    VIEW_CHANNEL: 'Permet aux membres de la guilde de voir un canal, qui comprend des messages de lecture dans les canaux de texte et de rejoindre les canaux vocaux',
    SEND_MESSAGES: 'Permet d\'envoyer des messages dans un canal et de créer des threads dans un forum (ne permet pas d\'envoyer des messages dans des threads)',
    SEND_TTS_MESSAGES: 'Permet d\'envoyer des messages / TTS',
    MANAGE_MESSAGES: 'Permet la suppression des autres messages des utilisateurs',
    EMBED_LINKS: 'Les liens envoyés par les utilisateurs avec cette autorisation seront automatiquement mis en forme',
    ATTACH_FILES: 'Permet de télécharger des images et des fichiers',
    READ_MESSAGE_HISTORY: 'Permet de lire l\'historique des messages',
    MENTION_EVERYONE: 'Permet d\'utiliser la balise @Everyone pour informer tous les utilisateurs dans une chaîne et la balise @here pour informer tous les utilisateurs en ligne dans un canal',
    USE_EXTERNAL_EMOJIS: 'Permet l\'utilisation d\'emojis personnalisés à partir d\'autres serveurs',
    VIEW_GUILD_INSIGHTS: 'Permet de visualiser les informations sur la guilde',
    CONNECT: 'Permet de rejoindre un canal vocal',
    SPEAK: 'Permet de parler dans un canal vocal',
    MUTE_MEMBERS: 'Permet de muter les membres dans un canal vocal',
    DEAFEN_MEMBERS: 'Permet d\'empêcher des membres d\'écouter dans un canal vocal',
    MOVE_MEMBERS: 'Permet de déplacer les membres entre les canaux vocaux',
    USE_VAD: 'Permet d\'utiliser la détection de l\'activité vocale dans un canal vocal',
    CHANGE_NICKNAME: 'Permet de modifier son propre surnom',
    MANAGE_NICKNAMES: 'Permet de modifier les surnoms des autres utilisateurs',
    MANAGE_ROLES: 'Permet la gestion et l\'édition des rôles',
    MANAGE_WEBHOOKS: 'Permet la gestion et l\'édition de webhooks',
    MANAGE_GUILD_EXPRESSIONS: 'Permet la gestion et l\'édition des emojis, des autocollants et des sons du soundboard',
    USE_APPLICATION_COMMANDS: 'Permet aux membres d\'utiliser des commandes d\'application, y compris les commandes de slash et les commandes de menu contextuel.',
    REQUEST_TO_SPEAK: 'Permet de demander de parler dans les canaux de scène. (Cette autorisation est en cours de développement actif et peut être modifiée ou supprimée.)',
    MANAGE_EVENTS: 'Permet de créer, d\'édition et de supprimer des événements planifiés',
    MANAGE_THREADS: 'Permet de supprimer et d\'archiver des fils et de visualiser tous les fils privés',
    CREATE_PUBLIC_THREADS: 'Permet de créer des fils publiques et d\'annonce',
    CREATE_PRIVATE_THREADS: 'Permet de créer des fils privés',
    USE_EXTERNAL_STICKERS: 'Permet l\'utilisation d\'autocollants personnalisés d\'autres serveurs',
    SEND_MESSAGES_IN_THREADS: 'Permet d\'envoyer des messages dans des threads',
    USE_EMBEDDED_ACTIVITIES: 'Permet d\'utiliser des activités (applications avec l\'indicateur intégré) dans un canal vocal',
    MODERATE_MEMBERS: 'Permet à la synchronisation des utilisateurs de les empêcher d\'envoyer ou de réagir aux messages dans le chat et les threads, et de parler dans les canaux vocaux et de scène',
    VIEW_CREATOR_MONETIZATION_ANALYTICS: 'Permet de visualiser les informations sur l\'abonnement au rôle',
    USE_SOUNDBOARD: 'Permet d\'utiliser le soundboard dans un canal vocal',
    USE_EXTERNAL_SOUNDS: 'Permet l\'utilisation des sons du soundboard personnalisés à partir d\'autres serveurs',
    SEND_VOICE_MESSAGES: 'Permet d\'envoyer des messages vocaux',
  };